apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-db-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: keycloak-db-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: {{ .Values.externalSecrets.dbSecret.secretsManagerName }}
        property: username
    - secretKey: password
      remoteRef:
        key: {{ .Values.externalSecrets.dbSecret.secretsManagerName }}
        property: password
