apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: {{ .Values.istio.gateway.name }}
  {{- with .Values.istio.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    istio: {{ .Values.istio.gateway.selector }}
  servers:
    - hosts:
        - {{ .Values.istio.hosts.host }}
      port:
        number: 80
        name: http
        protocol: HTTP2
      tls:
        httpsRedirect: true
    - hosts:
        - {{ .Values.istio.hosts.host }}
      port:
        number: 443
        name: https
        protocol: HTTP2
