apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argo-cd
  namespace: argo
spec:
  parentRefs:
    - name: {{ .Values.istio.httpRoute.gatewayName }}
      namespace: istio-system
  hostnames: [ {{ .Values.istio.httpRoute.domain }} ]
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ .Values.istio.httpRoute.service.name }}
          port: {{ .Values.istio.httpRoute.service.port }}
