apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ .Values.istio.virtualservice.name }}
spec:
  hosts:
    - {{ .Values.istio.hosts.host }}
  gateways:
    - {{ .Values.istio.gateway.name }}
  http:
    - name: argo-cd
      match:
        - uri:
            prefix: /
      route:
        - destination:
            host: argocd-server.argo.svc.cluster.local
            port:
              number: 80
