apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubecost-cost-analyzer
  namespace: argo
spec:
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
  sources:
    - repoURL: public.ecr.aws/kubecost
      targetRevision: 2.6.5
      chart: cost-analyzer
      helm:
        valueFiles:
          - values-eks-cost-monitoring.yaml
          - $values/infrastructure/kubecost/values/values.yaml
    - repoURL: https://github.com/lomeone/k8s-chart
      targetRevision: main
      ref: values
  project: helm-chart
