apiVersion: v1
kind: Namespace
metadata:
  name: arc-system
  labels:
    istio.io/dataplane-mode: ambient
---
apiVersion: v1
kind: Namespace
metadata:
  name: arc-runners
  labels:
    istio.io/dataplane-mode: ambient
