apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
spec:
  auth:
    strategy: anonymous
  deployment:
    cluster_wide_access: true
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 128Mi
  external_services:
    grafana:
      dashboards:
        - name: "Istio Service Dashboard"
        - name: "Istio Workload Dashboard"
        - name: "Istio Mesh Dashboard"
        - name: "Istio Control Plane Dashboard"
        - name: "Istio Performance Dashboard"
{{/*        - name: "Istio Wasm Extension Dashboard"*/}}
      enabled: true
      internal_url: http://grafana-service.observability.svc.cluster.local:3000
      external_url: http://grafana-service.observability.svc.cluster.local:3000
      auth:
        type: basic
        username: admin
        password: start
    prometheus:
      url: http://{{- include "prometheus.name" . }}.istio-system.svc.cluster.local:9090
    tracing:
      enabled: true
      provider: jaeger
      internal_url: http://jaeger-inmemory-instance-collector.observability.svc.cluster.local:16686
      use_grpc: false
{{/*      grpc_port: 4317*/}}
