apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: keycloak-httproute
spec:
  parentRefs:
    - name: public-gateway
      namespace: istio-gateway
  hostnames: [ {{ .Values.hostName }}]
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ .Values.keycloakName }}-service
          port: 8080
