istio:
  gateway:
    name: argocd-gw
    annotations:
      external-dns.alpha.kubernetes.io/ttl: "5m"
    selector: ingressgateway
  virtualservice:
    name: argocd-vs
  hosts:
    host: argo-cd.lomeone.com
