image:
  repo: 396428372646.dkr.ecr.ap-northeast-2.amazonaws.com/quay-io/kiali/kiali-operator

cr:
  create: true
  namespace: istio-system
  spec:
    auth:
      strategy: "anonymous"
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        memory: 128Mi
