apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: ztunnel-podmonitor
  namespace: istio-system
  labels:
    istio: "true"
spec:
  selector:
    matchLabels:
      app: ztunnel
  namespaceSelector:
    matchNames:
      - istio-system
  podMetricsEndpoints:
    - port: ztunnel-stats
      interval: 15s
      path: /metrics
