apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: jaeger-inmemory-instance
spec:
  image: 396428372646.dkr.ecr.ap-northeast-2.amazonaws.com/docker-hub/jaegertracing/jaeger:latest
  ports:
    - name: jaeger
      port: 16686
  resources:
    requests:
      cpu: 50m
      memory: 32Mi
    limits:
      memory: 32Mi
  config:
    service:
      extensions: [ jaeger_storage, jaeger_query ]
      pipelines:
        traces:
          receivers: [ otlp ]
          exporters: [ jaeger_storage_exporter ]
    extensions:
      jaeger_query:
        storage:
          traces: memstore
      jaeger_storage:
        backends:
          memstore:
            memory:
              max_traces: 100000
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    exporters:
      jaeger_storage_exporter:
        trace_storage: memstore
