apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datadog
  namespace: argo
spec:
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      ## when error: Resource is too big to fit in 262144 bytes allowed annotation size.
      ## https://argo-cd.readthedocs.io/en/latest/user-guide/sync-options/#server-side-apply
      - ServerSideApply=true
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
  sources:
    - repoURL: https://helm.datadoghq.com
      chart: datadog
      targetRevision: 3.100.0
      helm:
        valueFiles:
          - $values/infrastructure/datadog/values/values.yaml
    - repoURL: https://github.com/lomeone/k8s-chart
      targetRevision: main
      ref: values
  project: helm-chart
