repositories:
  - name: apollographql
    url: oci://ghcr.io/apollographql/helm-charts

releases:
  - name: router
    namespace: apollo
    chart: apollographql/router
    version: 2.14.0
    values:
      - values/router.yaml
  - name: addons
    namespace: apollo
    chart: ./addons
    values:
      - values/addons.yaml
