controller:
  image:
    registry: 396428372646.dkr.ecr.ap-northeast-2.amazonaws.com/quay-io
  resources:
    requests:
      cpu: 10m
      memory: 256Mi
    limits:
      memory: 256Mi
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

dashboard:
  image:
    registry: 396428372646.dkr.ecr.ap-northeast-2.amazonaws.com/quay-io
