controller:
  image:
    registry: 396428372646.dkr.ecr.ap-northeast-2.amazonaws.com/quay-io
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 64Mi

dashboard:
  image:
    registry: 396428372646.dkr.ecr.ap-northeast-2.amazonaws.com/quay-io
