apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: istio-prometheus
  namespace: istio-system
spec:
  # Prometheus 인스턴스를 관리할 서비스 어카운트
  serviceAccountName: prometheus-istio-sa # ServiceAccount 이름
  # 스크랩 설정을 위한 PodMonitor와 ServiceMonitor를 찾을 selector
  serviceMonitorSelector:
    matchLabels:
      istio: "true"
  podMonitorSelector:
    matchLabels:
      istio: "true"
  # 원격 쓰기(Remote Write) 설정
  remoteWrite:
    - url: http://prometheus-stack-kube-prom-prometheus.observability.svc.cluster.local:9090/api/v1/write
      queueConfig:
        capacity: 2000
      # istio-system 네임스페이스의 Prometheus에서 수집한 메트릭에 레이블 추가
      writeRelabelConfigs:
        - sourceLabels: [__name__]
          regex: ^(istio_.*)$
          action: keep # 메트릭 이름이 istio_로 시작하는 것만 남김
        - targetLabel: job
          replacement: "istio-system-scrape"
          action: replace
