releases:
  - name: karpenter
    namespace: kube-system
    chart: oci://public.ecr.aws/karpenter/karpenter
    version: 1.5.1
    values:
      - values/karpenter.yaml

  # Register karpenter node
  - name: karpenter-node
    namespace: kube-system
    chart: ./node

