releases:
  - name: karpenter-crd
    namespace: kube-system
    chart: oci://public.ecr.aws/karpenter/karpenter-crd
    version: 1.2.1

  - name: karpenter
    namespace: kube-system
    chart: oci://public.ecr.aws/karpenter/karpenter
    version: 1.2.1
    values:
      - values/karpenter.yaml

  # Register karpenter node
  - name: karpenter-node
    namespace: kube-system
    chart: ./node

