apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argo
spec:
  destination:
    namespace: crossplane-system
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
  sources:
    - repoURL: https://charts.crossplane.io/stable
      chart: crossplane
      targetRevision: 1.20.1
      helm:
        valueFiles:
          - $values/crossplane/values/values.yaml
    - repoURL: https://github.com/lomeone/helm-chart-infra
      targetRevision: main
      ref: values
  project: helm-chart
