apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-provider
  namespace: argo
spec:
  destination:
    namespace: crossplane-system
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
  source:
    path: infrastructure/crossplane/provider
    repoURL: https://github.com/lomeone/k8s-chart
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  project: helm-chart
