apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istiod-servicemonitor
  namespace: istio-system
  {{ with .Values.istio.monitorMatchLabels }}
  labels:
    {{ toYaml . | nindent 4 }}
  {{ end }}
spec:
  selector:
    matchLabels:
      app: istiod
      istio: pilot
  namespaceSelector:
    matchNames:
      - istio-system
  endpoints:
    - port: http-monitoring
      interval: 15s
      path: /metrics
