repositories:
  - name: istio
    url: https://istio-release.storage.googleapis.com/charts

  - name: kiali
    url: https://kiali.org/helm-charts

releases:
  # Istio Control Plane
  - name: istio-base
    namespace: istio-system
    chart: istio/base
    version: 1.28.3

  - name: istiod
    namespace: istio-system
    chart: istio/istiod
    version: 1.28.3
    values:
      - values/istiod.yaml
    needs:
      - istio-system/istio-base

  - name: istio-cni
    namespace: istio-system
    chart: istio/cni
    version: 1.28.3
    values:
      - values/cni.yaml
    needs:
      - istio-system/istio-base

  # Istio Data Plane
  - name: ztunnel
    namespace: istio-system
    chart: istio/ztunnel
    version: 1.28.3
    values:
      - values/ztunnel.yaml
    needs:
      - istio-system/istiod

  - name: external-istio-gateway
    namespace: istio-gateway
    chart: ./istio-gateway
    values:
      - values/external-gateway.yaml
    needs:
      - istio-system/istiod

#  - name: internal-istio-gateway
#    namespace: istio-gateway
#    chart: ./istio-gateway
#    values:
#      - values/private-gateway.yaml
#    needs:
#      - istio-system/istiod

  - name: istio-addons
    namespace: istio-system
    chart: ./addons
    values:
      - values/addons.yaml
    needs:
      - istio-system/istiod
