repositories:
  - name: istio
    url: https://istio-release.storage.googleapis.com/charts

  - name: kiali
    url: https://kiali.org/helm-charts

releases:
  # Istio Control Plane
  - name: istio-base
    namespace: istio-system
    chart: istio/base
    version: 1.26.0

  - name: istiod
    namespace: istio-system
    chart: istio/istiod
    version: 1.26.0
    values:
      - values/istiod.yaml

  - name: istio-cni
    namespace: istio-system
    chart: istio/cni
    version: 1.26.0
    values:
      - values/istio-cni.yaml

  # Istio Data Plane
  - name: ztunnel
    namespace: istio-system
    chart: istio/ztunnel
    version: 1.26.0
    values:
      - values/ztunnel.yaml

  - name: istio-ingress
    namespace: istio-system
    chart: istio/gateway
    version: 1.26.0
    values:
      - values/istio-ingress.yaml

  - name: kiali-operator
    namespace: kiali-operator
    chart: kiali/kiali-operator
    version: 2.10.0
    values:
      - values/kiali-operator.yaml

  - name: addons
    namespace: istio-system
    chart: ./addons
