apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.gatewayName }}
  namespace: istio-gateway
spec:
  minAvailable: 1
  selector:
    matchLabels:
      gateway.networking.k8s.io/gateway-name: {{ .Values.gatewayName }}
