repositories:
  - name: argo
    url: https://argoproj.github.io/argo-helm

releases:
  - name: argocd
    namespace: argo
    chart: argo/argo-cd
    version: 9.3.7
    values:
      - ./values/argo-cd.yaml

  - name: argocd-image-updater
    namespace: argo
    chart: argo/argocd-image-updater
    version: 1.0.5
    values:
      - ./values/argocd-image-updater.yaml

#  - name: argo-rollouts
#    namespace: argo
#    chart: argo/argo-rollouts
#    version: 2.40.5
#    values:
#      - ./values/argo-rollouts.yaml

  - name: argo-addons
    namespace: argo
    chart: ./addons
