repositories:
  - name: argo
    url: https://argoproj.github.io/argo-helm

---

releases:
  - name: argocd
    namespace: argo
    chart: argo/argo-cd
    version: 7.8.7
    values:
      - ./values/argo-cd.yaml

  - name: argo-addons
    namespace: argo
    chart: ./addons
