alertmanager:
  enabled: false
grafana:
  enabled: false
  forceDeployDatasources: false
  forceDeployDashboards: true
  defaultDashboardsEnabled: true
  operator:
    dashboardsConfigMapRefEnabled: true
    matchLabels:
      dashboard: grafana
kubeProxy:
  enabled: false
kube-state-metrics:
  image:
    registry: 396428372646.dkr.ecr.ap-northeast-2.amazonaws.com/k8s
nodeExporter:
  enabled: false
prometheusOperator:
  tls:
    enabled: false
  admissionWebhooks:
    enabled: false
    annotations:
      argocd.argoproj.io/hook: PreSync
      argocd.argoproj.io/hook-delete-policy: HookSucceeded
    mutatingWebhookConfiguration:
      annotations:
        argocd.argoproj.io/hook: PreSync

    validatingWebhookConfiguration:
      annotations:
        argocd.argoproj.io/hook: PreSync

    deployment:
      tls:
        enabled: false
    patch:
      annotations:
        argocd.argoproj.io/hook: PreSync
        argocd.argoproj.io/hook-delete-policy: HookSucceeded
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 128Mi
  image:
    registry: 396428372646.dkr.ecr.ap-northeast-2.amazonaws.com/quay-io
  prometheusConfigReloader:
    image:
      registry: 396428372646.dkr.ecr.ap-northeast-2.amazonaws.com/quay-io

prometheus:
  prometheusSpec:
    image:
      registry: 396428372646.dkr.ecr.ap-northeast-2.amazonaws.com/quay-io
    enableRemoteWriteReceiver: true
    resources:
      requests:
        cpu: 100m
        memory: 1Gi
      limits:
        memory: 1Gi
cleanPrometheusOperatorObjectNames: true
