apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: {{ .Values.node.nodeClass.name }}
spec:
  amiFamily: {{ .Values.node.nodeClass.amiFamily }}
  {{- with .Values.node.nodeClass.amiSelectorTerms }}
  amiSelectorTerms:
  {{ toYaml . | indent 2 }}
  {{- end }}
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.eksCluster.name }}
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.eksCluster.name }}
  role: "KarpenterNodeRole-{{ .Values.eksCluster.name }}"
  {{- with .Values.node.nodeClass.tags }}
  tags:
  {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
