prometheus:
  name: istio-prometheus
  image:
    registry: 396428372646.dkr.ecr.ap-northeast-2.amazonaws.com/quay-io
    repository: prometheus/prometheus
    tag: v3.10.0
  serviceAccount:
    name: istio-prometheus
  serviceMonitor:
    selector:
      matchLabels:
        app: istio
  podMonitor:
    selector:
      matchLabels:
        app: istio

serviceEntry:
  entries:
    - name: aws-resource
      hosts:
        - "*.ap-northeast-2.amazonaws.com"
      ports:
        - number: 443
          name: aws
          protocol: HTTPS
      location: MESH_EXTERNAL
      resolution: DNS
      exportTo:
        - "*"
