apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: "kail-gw"
  {{- with .Values.kialiGateway.istio.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    istio: {{ .Values.kialiGateway.istio.ingress.selector }}
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP2
      hosts:
        - {{ .Values.kialiGateway.istio.domain }}
      tls:
        httpsRedirect: true
    - port:
        number: 443
        name: https
        protocol: HTTP2
      hosts:
        - {{ .Values.kialiGateway.istio.domain }}
