apiVersion: v1
kind: Service
metadata:
  name: prometheus-istio
  namespace: istio-system
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 9090
      protocol: TCP
      targetPort: web
  selector:
    app.kubernetes.io/name: prometheus
    prometheus: istio-prometheus
